### ISSUE TITLE
Can't comment on your post - Says sign in to comment even though I'm signed in

### ISSUE THREAD

**Issue by andytriboletti** [CORESPONSE/blog#5]
Thank you for this design.

I can't comment on https://coresponse.github.io/blog/instruction/concept/2020/03/25/concept_crank_II_v0.html

My comment would be:
I could not find 4x17 wood screw, 4 Pc. 4x35 wood screw in America from the list of parts.

But I used:
https://www.mcmaster.com/90006a119
https://www.mcmaster.com/90006a113

I think they will be close enough.

Thanks again

**Comment by andytriboletti** [comment]
I created a full shopping list of products for this project:
https://blog.andytriboletti.com/backup-ventilator-project/

**Comment by Tuebel** [comment]
Are you able to type into the textbox? I had to sign in for github.io again even though I have been logged in on github.com.

Thanks for the list! If it is okay for you, I would link it in the blog post.

**Comment by andytriboletti** [comment]
I just tried again after signing in and it worked. You have my permission to link or copy the shopping list.
